import type { PublicPerson } from '../../../types/api/people'

export interface Milestone {
  id: number,
  iid: number,
  project_id: number,
  title: string,
  description: string,
  state: string,
  created_at: string,
  updated_at: string,
  due_date: string,
  start_date: string,
  web_url: string,
}

export interface Pipeline {
  id: number,
  sha: string,
  ref: string,
  status: string,
  web_url: string,
}

export interface MergeRequest {
  id: number,
  iid: number,
  project_id: number,
  title: string,
  description: string,
  state: string,
  created_at: string,
  updated_at: string,
  target_branch: string,
  source_branch: string,
  upvotes: number,
  downvotes: number,
  author: PublicPerson,
  user: {
    can_merge: boolean,
  },
  assignee: PublicPerson | null,
  assignees: PublicPerson[],
  source_project_id: number,
  target_project_id: number,
  work_in_progress: boolean,
  merge_when_pipeline_succeeds: boolean,
  merge_status: string,
  merge_error: string | null,
  sha: string,
  merge_commit_sha: null | string,
  user_notes_count: number,
  discussion_locked: null | boolean,
  should_remove_source_branch: boolean,
  force_remove_source_branch: boolean,
  allow_collaboration: boolean,
  allow_maintainer_to_push: boolean,
  web_url: string,
  milestone: Milestone | null,
  time_stats: {
    time_estimate: number,
    total_time_spent: number,
    human_time_estimate: null | string,
    human_total_time_spent: null | string,
  },
  squash: boolean,
  subscribed: boolean,
  changes_count: string,
  merged_by: PublicPerson | null,
  merged_at: string | null,
  closed_by: PublicPerson | null,
  closed_at: string | null,
  latest_build_started_at: string | null,
  latest_build_finished_at: string | null,
  first_deployed_to_production_at: string | null,
  pipeline: Pipeline | null,
  diff_refs: {
    base_sha: string,
    head_sha: string,
    start_sha: string,
  },
  diverged_commits_count: number,
  rebase_in_progress: boolean,
  task_completion_status: {
    count: number,
    completed_count: number,
  },
}
