[versioning]
unified = ['/packages/*']
source = 'tag'

[changelog]
front_matter = """
id: index
title: Change Log"""

[mark_pr]
analyze_update = false
packages_as_labels = false
packages_table = true
packages_graph = false
attach_changelog = true

[publish]
registry = 'https://registry.npmjs.org'
cli_args = '--access public'

[update]
default_release_type = 'patch'
commit_via_platform = false
retry_via_platform_if_failed_via_vcs = false

[[update.release_type_overrides]]
type = 'none'
files_match = [
  '**/__tests__/**/*',
]

[update.graph]
strip_namespace = false

[notifications]
target = 'all'

[[plugins_v2]]
plugin = '@pvm/plugin-github'

[[plugins_v2]]
plugin = '@pvm/plugin-conventional-changelog'

[[plugins_v2]]
plugin = '@pvm/plugin-mattermost'
options = { team = 'tinkoff', channel = 'pvm-github', author = { name = 'pvm minion (github)', avatarEmoji = ':deciduous_tree:' } }
