name: 'pvm update'

on:
  push:
    branches:
      - 'master'

env:
  PVM_LL: silly

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          # Because of restriction that actions made with GITHUB_TOKEN are not trigger any actions
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - uses: ./.github/actions/setup
      - run: npm run build
      - run: npm exec pvm update
        env:
          GITHUB_TOKEN: ${{ secrets.TINKOFF_BOT_PAT }}

  docs:
    runs-on: ubuntu-latest
    container: mshipov/plantuml:1.0.4
    needs:
      - update
      - perf-test
    permissions:
      contents: read
      pages: write
    concurrency:
      group: docs
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 150
      - uses: ./.github/actions/build-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@master
        with:
          name: metrics
          path: website/build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build

  perf-test:
    runs-on: ubuntu-latest
    concurrency:
      group: docs
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup
      - run: npm run build
      - run: node scripts/perf/run.js
      - uses: actions/upload-artifact@master
        with:
          name: metrics
          path: public/
